version: '3'
services:
  jellyfin-telegram-notifier:
    container_name: jellyfin-telegram-notifier
    image: fahmula/jellyfin-telegram-notifier
    ports:
      - "5000:5000"  # Map host port 5000 to container port 5000
    volumes:
      - /app/log:/app/log  # Map the host directory to the container directory for logs
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - JELLYFIN_BASE_URL=${JELLYFIN_BASE_URL}
      - JELLYFIN_API_KEY=${JELLYFIN_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - SEASON_ADDED_WITHIN_X_DAYS=${SEASON_ADDED_WITHIN_X_DAYS}
      - EPISODE_PREMIERED_WITHIN_X_DAYS=${EPISODE_PREMIERED_WITHIN_X_DAYS}
    env_file:
      - .env
